#!/bin/bash
Write short paragraphs and cover one topic per paragraph
Long paragraphs discourage users from even trying to understand your material
Short paragraphs are easier to read and understand
Writing experts recommend paragraphs of no more than 150 words in three to eight sentences
